name: Build Examples

on: [workflow_dispatch]

jobs:
  build-android-example:
    name: Build Android
    runs-on: ubuntu-latest
    env:
      CC: clang
      CXX: clang++
#      CCACHE: 1

    steps:
      # strange but we cannot use ninja from NDK?
      - name: Setup Ninja
        uses: eliasku/gha-setup-ninja@master

      # See b/206099937. Hack needed to make ninja visible to cmake during NDK builds
      - name: Link Ninja binary
        run: |
          chmod +x ninja-build/ninja
          ln -s "${GITHUB_WORKSPACE}/ninja-build/ninja" "/usr/local/bin/ninja"

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          java-package: jdk # optional (jdk or jre) - defaults to jdk

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Install
        run: npm ci

      - name: Build EKX package
        run: npm run build

      - name: Link EKX package
        run: npm i
        working-directory: ./examples/2-drawing

      - name: Print versions
        run: |
          ninja --version
          cmake --version
          echo $CC $CXX
          java --version
          ccache --version
          node --version
          npm --version
          which ninja
          which ekx
        working-directory: ./examples/2-drawing

      - name: Build Android
        run: ekx android bundle -V
        working-directory: ./examples/2-drawing

  build-web-example:
    name: Build Web
    runs-on: ubuntu-latest
    env:
      EM_VERSION: 3.1.32
      EM_CACHE_FOLDER: 'emsdk-cache'
      CC: clang
      CXX: clang++
      CCACHE: 1
    steps:
      # setup native build tools
      - name: Setup system cache
        id: cache-system-libraries
        uses: actions/cache@v3
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}

      - name: Setup Ninja
        uses: eliasku/gha-setup-ninja@master

      - name: Link Ninja binary
        run: |
          chmod +x ninja-build/ninja
          ln -s "${GITHUB_WORKSPACE}/ninja-build/ninja" "/usr/local/bin/ninja"

      - name: Install CCache
        uses: eliasku/install-ccache-action@master

      - name: Setup CCache
        uses: eliasku/ccache-action@main
        with:
          key: ${{ runner.os }}

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v12
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Setup EKX package
        run: npm ci

      - name: Build EKX package
        run: npm run build

      - name: Link EKX package
        run: npm i
        working-directory: ./examples/2-drawing

      - name: Print versions
        run: |
          ninja --version
          cmake --version
          echo $CC $CXX
          java --version
          ccache --version
          node --version
          npm --version
          which ninja
          which ekx

      - name: Build
        run: cd ./examples/2-drawing && ekx web -V
#        working-directory: ./examples/2-drawing
