source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'

target 'app-ios' do
  use_frameworks! :linkage => :static
  # TEMPLATE DEPENDENCIES
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end
